// src/pages/Setting/components/GeneralSetting/components/ModelProviderSetting.vue
<script setup lang="ts">
/**
 * 模型供应商设置组件（Vue 版 ModelProviderSetting）
 * 组合头部刷新、错误提示与供应商卡片网格，展开状态与刷新流程本地管理
 */
import { onUnmounted, ref } from 'vue';
import { toastQueue } from '@/services/toast';
import { useTranslation } from '@/composables/useTranslation';
import { useModelProviderStore } from '@/store/pinia/modelProvider';
import ProviderHeader from './ModelProviderSetting/components/ProviderHeader.vue';
import ProviderGrid from './ModelProviderSetting/components/ProviderGrid.vue';
import ErrorAlert from './ModelProviderSetting/components/ErrorAlert.vue';

const { t } = useTranslation();
const providerStore = useModelProviderStore();

// 进行中刷新请求的中止控制器
const abortController = ref<AbortController | null>(null);
// 已展开的供应商 Key 集合
const expandedProviders = ref<Set<string>>(new Set());

// 组件卸载时中止进行中的刷新请求
onUnmounted(() => {
  abortController.value?.abort();
});

/** 手动刷新供应商数据（成功/失败均有 Toast 反馈） */
const handleRefresh = () => {
  // 中止上一次未完成的请求
  abortController.value?.abort();

  const controller = new AbortController();
  abortController.value = controller;

  void providerStore
    .refreshModelProvider(controller.signal)
    .then(() => {
      if (providerStore.error) {
        toastQueue.error(providerStore.error);
      } else {
        toastQueue.success(t(($) => $.setting.modelProvider.refreshSuccess));
      }
    })
    .catch((err: unknown) => {
      const errorMessage = err instanceof Error ? err.message : t(($) => $.setting.modelProvider.refreshFailed);
      toastQueue.error(errorMessage);
    })
    .finally(() => {
      abortController.value = null;
    });
};

/**
 * 切换供应商卡片的展开/折叠状态
 * @param providerKey 供应商唯一标识
 */
const handleToggleProvider = (providerKey: string) => {
  const newSet = new Set(expandedProviders.value);
  if (newSet.has(providerKey)) {
    newSet.delete(providerKey);
  } else {
    newSet.add(providerKey);
  }
  expandedProviders.value = newSet;
};
</script>

<template>
  <div class="flex w-full flex-col gap-6">
    <ProviderHeader
      :loading="providerStore.loading"
      :last-update="providerStore.lastUpdate"
      @refresh="handleRefresh"
    />

    <ErrorAlert :error="providerStore.error" />

    <ProviderGrid
      :providers="providerStore.providers"
      :expanded-providers="expandedProviders"
      @toggle-provider="handleToggleProvider"
    />
  </div>
</template>

// src/pages/Setting/components/GeneralSetting/components/ModelProviderSetting.tsx
import { useEffect, useState, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { refreshModelProvider } from '@/store/slices/modelProviderSlice';
import { RootState, AppDispatch } from '@/store';
import { toastQueue } from '@/services/toast';
import { useTranslation } from 'react-i18next';
import { ProviderHeader } from './ModelProviderSetting/components/ProviderHeader';
import { ProviderGrid } from './ModelProviderSetting/components/ProviderGrid';
import { ErrorAlert } from './ModelProviderSetting/components/ErrorAlert';

const ModelProviderSetting: React.FC = () => {
  const dispatch = useDispatch<AppDispatch>();
  const { t } = useTranslation();
  const { providers, loading, error, lastUpdate } = useSelector(
    (state: RootState) => state.modelProvider
  );
  const [abortController, setAbortController] = useState<AbortController | null>(null);
  const [expandedProviders, setExpandedProviders] = useState<Set<string>>(new Set());

  useEffect(() => {
    return () => {
      if (abortController) {
        abortController.abort();
      }
    };
  }, [abortController]);

  const handleRefresh = useCallback(() => {
    if (abortController) {
      abortController.abort();
    }

    const controller = new AbortController();
    setAbortController(controller);

    dispatch(refreshModelProvider())
      .unwrap()
      .then(() => {
        toastQueue.success(t($ => $.setting.modelProvider.refreshSuccess));
      })
      .catch((err: unknown) => {
        const errorMessage = err instanceof Error ? err.message : t($ => $.setting.modelProvider.refreshFailed);
        toastQueue.error(errorMessage);
      })
      .finally(() => {
        setAbortController(null);
      });
  }, [dispatch, t, abortController]);

  const handleToggleProvider = useCallback((providerKey: string) => {
    setExpandedProviders((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(providerKey)) {
        newSet.delete(providerKey);
      } else {
        newSet.add(providerKey);
      }
      return newSet;
    });
  }, []);

  return (
    <div className="flex flex-col gap-6 w-full">
      <ProviderHeader
        loading={loading}
        onRefresh={handleRefresh}
        lastUpdate={lastUpdate}
      />

      <ErrorAlert error={error} />

      <ProviderGrid
        providers={providers}
        expandedProviders={expandedProviders}
        onToggleProvider={handleToggleProvider}
      />
    </div>
  );
};

export default ModelProviderSetting;
