// src/components/OpenExternalBrowserButton/OpenExternalBrowserButton.vue
<script setup lang="ts">
/**
 * 可以点击打开外部浏览器的按钮（Vue 版 OpenExternalBrowserButton）
 */
import { ExternalLink } from 'lucide-vue-next';
import { Button } from '@/components/ui-vue/button';
import { useNavigateToExternalSite } from '@/composables/useNavigateToExternalSite';

const props = withDefaults(
  defineProps<{
    // 要打开的网址
    siteUrl: string | undefined;
    className?: string;
  }>(),
  { className: '' },
);

const { navToExternalSite } = useNavigateToExternalSite();

// 跳转到外部网站（纯 Web 环境直接新开标签页）
const navToOfficialSite = () => {
  if (props.siteUrl) {
    navToExternalSite(props.siteUrl);
  }
};
</script>

<template>
  <Button v-if="props.siteUrl" variant="ghost" :class="props.className" @click="navToOfficialSite">
    <ExternalLink class="h-4 w-4" />
  </Button>
</template>

// src/components/OpenExternalBrowserButton/index.tsx
/**
 * 可以点击打开外部浏览器的按钮
 */

import { useNavigateToExternalSite } from "@/hooks/useNavigateToExternalSite"
import { ExternalLink } from "lucide-react"
import { Button } from "@/components/ui/button"

interface ButtonProps {
  // 要打开的网址
  siteUrl: string | undefined
  className?: string
}

const OpenExternalBrowserButton: React.FC<ButtonProps> = ({
  siteUrl,
  className = '',
}) => {

  const {
    navToExternalSite,
  } = useNavigateToExternalSite()

  if (!siteUrl) {
    return <></>
  }

  // 跳转到外部网站
  const navToOfficialSite = () => {
    navToExternalSite(siteUrl)
  }

  return (
    <Button
      variant="ghost"
      className={className}
      onClick={navToOfficialSite}
    >
      <ExternalLink className="h-4 w-4" />
    </Button>
  )
}


export default OpenExternalBrowserButton
