// src/pages/Model/CreateModel/components/ModelSidebar.vue
<script setup lang="ts">
/**
 * 模型选择侧边栏（Vue 版 ModelSidebar）
 * 支持按钮元素压缩：根据屏幕尺寸调整按钮、Avatar 和文字大小
 */
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ArrowLeft } from 'lucide-vue-next';
import FilterInput from '@/components/FilterInput.vue';
import { Button } from '@/components/ui-vue/button';
import { Avatar } from '@/components/ui-vue/avatar';
import { useDebouncedFilter } from '@/composables/useDebouncedFilter';
import { useModelProviderStore } from '@/store/pinia/modelProvider';
import { useResponsive } from '@/composables/useResponsive';
import { useTranslation } from '@/composables/useTranslation';
import { getProviderLogoUrl } from '@/utils/providerUtils';
import type { ModelProviderKeyEnum } from '@/utils/enums';

const props = defineProps<{
  // 当前选中的大模型
  value: ModelProviderKeyEnum;
}>();

const emit = defineEmits<{ (e: 'change', value: ModelProviderKeyEnum): void }>();

const { t } = useTranslation();
const router = useRouter();
const { isDesktop, isMobile } = useResponsive();
const providerStore = useModelProviderStore();

// 从 Store 获取所有供应商
const providers = computed(() => providerStore.providers);

// 本地状态：过滤文本
const filterText = ref('');
const {
  filteredList: filteredProviders,
} = useDebouncedFilter(
  filterText,
  providers,
  (provider) =>
    provider.providerName.toLocaleLowerCase().includes(filterText.value.toLocaleLowerCase()),
);

// 按钮样式根据屏幕尺寸压缩
const buttonClassName = computed(
  () => `w-full flex justify-start rounded-none ${!isDesktop.value ? 'py-4' : 'py-5'}`,
);

// Avatar 大小根据屏幕尺寸压缩
const avatarClassName = computed(() => `${!isDesktop.value ? 'h-7 w-7' : 'h-8 w-8'}`);

// 文字大小根据屏幕尺寸压缩
const textSize = computed(() => `${!isDesktop.value ? 'text-sm' : 'text-base'}`);

// 容器 padding 根据屏幕尺寸调整
const containerPadding = computed(() => (!isDesktop.value ? 'p-1' : 'p-2'));
</script>

<template>
  <nav
    :aria-label="t('common.a11y.modelProviderNav') as string"
    :class="`flex h-full w-60 flex-col items-center justify-start ${containerPadding}`"
  >
    <!-- 表头部分 -->
    <div :class="`w-full border-b border-gray-300 ${!isDesktop ? 'p-1' : 'p-2'}`">
      <div class="flex w-full items-center justify-between pb-2">
        <!-- 返回上一页按钮 -->
        <Button
          v-if="!isMobile"
          variant="ghost"
          class="h-8 w-8 rounded-lg p-0"
          @click="router.push('/model/table')"
        >
          <ArrowLeft size="16" />
        </Button>
        <span class="text-lg">{{ t('model.modelProvider') }}</span>
      </div>
      <FilterInput
        v-model="filterText"
        :placeholder="t('model.searchModel') as string"
        class="w-full rounded-lg"
      />
    </div>
    <!-- 可供选择的供应商列表 -->
    <div class="w-full pb-2">
      <Button
        v-for="provider in filteredProviders"
        :key="provider.providerKey"
        variant="ghost"
        :class="`${buttonClassName} ${provider.providerKey === props.value ? 'bg-gray-200' : ''}`"
        :aria-current="provider.providerKey === props.value ? 'page' : undefined"
        :title="provider.providerName"
        @click="emit('change', provider.providerKey as ModelProviderKeyEnum)"
      >
        <Avatar :class="avatarClassName">
          <img
            :src="getProviderLogoUrl(provider.providerKey)"
            :alt="provider.providerName"
          />
        </Avatar>
        <span :class="`pl-2 ${textSize}`">
          {{ provider.providerName }}
        </span>
      </Button>
    </div>
  </nav>
</template>

// src/pages/Model/CreateModel/components/ModelSidebar.tsx
import { useDebouncedFilter } from "@/components/FilterInput/hooks/useDebouncedFilter";
import FilterInput from "@/components/FilterInput";
import { useNavigate } from "react-router-dom";
import { ModelProviderKeyEnum } from "@/utils/enums";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar } from "@/components/ui/avatar";
import { useState } from "react";
import { useSelector } from "react-redux";
import { useTranslation } from "react-i18next";
import { RootState } from "@/store";
import { useResponsive } from "@/hooks/useResponsive";
import { getProviderLogoUrl } from "@/utils/providerUtils";

interface ModelSidebarProps {
  // 当前选中的大模型
  value: ModelProviderKeyEnum;
  onChange: (value: ModelProviderKeyEnum) => void;
}

/**
 * 模型选择侧边栏
 * @description 支持按钮元素压缩：根据屏幕尺寸调整按钮、Avatar 和文字大小
 */
const ModelSidebar: React.FC<ModelSidebarProps> = ({
  value: selectedModelKey,
  onChange,
}) => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { isDesktop, isMobile } = useResponsive();

  // 从 Redux store 获取所有供应商
  const providers = useSelector(
    (state: RootState) => state.modelProvider.providers,
  );

  // 本地状态：过滤文本
  const [filterText, setFilterText] = useState<string>("");
  const { filteredList: filteredProviders } = useDebouncedFilter(
    filterText,
    providers,
    (provider) =>
      provider.providerName
        .toLocaleLowerCase()
        .includes(filterText.toLocaleLowerCase()),
  );

  // 按钮样式根据屏幕尺寸压缩
  const buttonClassName = `w-full flex justify-start rounded-none ${
    !isDesktop ? "py-4" : "py-5"
  }`;

  // Avatar 大小根据屏幕尺寸压缩
  const avatarClassName = `${!isDesktop ? "h-7 w-7" : "h-8 w-8"}`;

  // 文字大小根据屏幕尺寸压缩
  const textSize = `${!isDesktop ? "text-sm" : "text-base"}`;

  // 容器 padding 根据屏幕尺寸调整
  const containerPadding = !isDesktop ? "p-1" : "p-2";

  return (
    <nav
      aria-label={t(($) => $.common.a11y.modelProviderNav)}
      className={`flex flex-col items-center justify-start h-full w-60 ${containerPadding}`}
    >
      {/* 表头部分 */}
      <div
        className={`border-b border-gray-300 w-full ${!isDesktop ? "p-1" : "p-2"}`}
      >
        <div className="flex items-center justify-between w-full pb-2">
          {/* 返回上一页按钮 */}
          {!isMobile && (
            <Button
              variant="ghost"
              className="rounded-lg h-8 w-8 p-0"
              onClick={() => navigate("/model/table")}
            >
              <ArrowLeft size={16} />
            </Button>
          )}
          <span className="text-lg">{t(($) => $.model.modelProvider)}</span>
        </div>
        <FilterInput
          value={filterText}
          onChange={setFilterText}
          placeholder={t(($) => $.model.searchModel)}
          className={`w-full rounded-lg`}
        />
      </div>
      {/* 可供选择的 */}
      <div className="pb-2 w-full">
        {filteredProviders.map((provider) => {
          return (
            <Button
              key={provider.providerKey}
              variant="ghost"
              className={`${buttonClassName} ${
                provider.providerKey === selectedModelKey && "bg-gray-200"
              }`}
              aria-current={provider.providerKey === selectedModelKey ? 'page' : undefined}
              title={provider.providerName}
              onClick={() =>
                onChange(provider.providerKey as ModelProviderKeyEnum)
              }
            >
              <Avatar className={avatarClassName}>
                <img
                  src={getProviderLogoUrl(provider.providerKey)}
                  alt={provider.providerName}
                />
              </Avatar>
              <span className={`pl-2 ${textSize}`}>
                {provider.providerName}
              </span>
            </Button>
          );
        })}
      </div>
    </nav>
  );
};

export default ModelSidebar;
