// src/pages/Chat/components/ModelSelect/ModelSelect.vue
<script setup lang="ts">
/**
 * 模型选择视图（Vue 版 ModelSelect）
 * 新建聊天时配置聊天模型：模型多选表格、确认按钮、搜索过滤、已选标签预览
 */
import { computed, h, ref } from 'vue';
import type { ColumnDef, TableFeatures } from '@tanstack/table-core';
import { Menu, Trash2 } from 'lucide-vue-next';
import { isUndefined } from 'es-toolkit';
import FilterInput from '@/components/FilterInput.vue';
import { Button } from '@/components/ui-vue/button';
import { Checkbox } from '@/components/ui-vue/checkbox';
import { Badge } from '@/components/ui-vue/badge';
import { DataTable } from '@/components/ui-vue/data-table';
import { useCurrentSelectedChat } from '@/composables/useCurrentSelectedChat';
import { useBasicModelTable } from '@/composables/useBasicModelTable';
import { useResponsive } from '@/composables/useResponsive';
import { useChatStore } from '@/store/pinia/chat';
import { useChatPageStore } from '@/store/pinia/chatPage';
import { useModelStore } from '@/store/pinia/model';
import { toastQueue } from '@/services/toast';
import { useTranslation } from '@/composables/useTranslation';
import type { Chat } from '@/types/chat';
import type { Model } from '@/types/model';

const { t } = useTranslation();
const { isMobile } = useResponsive();
const chatStore = useChatStore();
const chatPageStore = useChatPageStore();
const modelStore = useModelStore();
const selectedChat = useCurrentSelectedChat();

// Content 三级分支保证本组件仅在已选中聊天时渲染
const typedSelectedChat = computed(() => selectedChat.value as Chat);

const { filterText, filteredModels, setFilterText, tableColumns } = useBasicModelTable();

const models = computed(() => modelStore.models);
const loading = computed(() => modelStore.loading);

// 选中的模型ID的列表
const checkedModelIdList = ref<string[]>([]);

/** 添加选中的ID */
const addCheckModelId = (model: Model) => {
  checkedModelIdList.value = [...checkedModelIdList.value, model.id];
};

/** 删除选中的ID */
const deleteCheckModelId = (model: Model) => {
  const idx = checkedModelIdList.value.findIndex((item) => item === model.id);
  if (idx !== -1) {
    const newList = [...checkedModelIdList.value];
    newList.splice(idx, 1);
    checkedModelIdList.value = newList;
  }
};

// 从 Store 中计算出已选模型列表
const checkedModelList = computed<Model[]>(() => {
  const list: Model[] = [];
  checkedModelIdList.value.forEach((id) => {
    const model = models.value.find((item) => item.id === id);
    if (!isUndefined(model)) {
      list.push(model);
    }
  });
  return list;
});

// 表格相关配置（添加选择列）
const columns = computed<ColumnDef<TableFeatures, Model>[]>(() => [
  {
    id: 'selected',
    header: '',
    cell: ({ row }) =>
      h(Checkbox, {
        modelValue: checkedModelIdList.value.includes(row.original.id),
        'onUpdate:modelValue': (checked: boolean | 'indeterminate') => {
          if (checked) {
            addCheckModelId(row.original);
          } else {
            deleteCheckModelId(row.original);
          }
        },
      }),
  },
  ...tableColumns.value,
]);

// 确认按钮的 loading 状态
const confirmLoading = ref(false);

/** 点击确定创建聊天（写入聊天模型配置） */
const onConfirm = async () => {
  if (checkedModelIdList.value.length <= 0) {
    toastQueue.info(t('chat.selectModelHint') as string);
    return;
  }

  confirmLoading.value = true;

  try {
    await chatStore.editChat({
      chat: {
        ...typedSelectedChat.value,
        chatModelList: checkedModelIdList.value.map((id) => ({
          modelId: id,
          chatHistoryList: [],
        })),
      },
    });

    toastQueue.success(t('chat.configureChatSuccess') as string);
  } catch {
    toastQueue.error(t('chat.configureChatFailed') as string);
  }

  confirmLoading.value = false;
};
</script>

<template>
  <div class="flex h-full w-full flex-col">
    <div class="flex h-12 w-full justify-between pl-4 pr-4" role="toolbar" :aria-label="t('common.a11y.modelToolbar') as string">
      <div class="flex h-full flex-wrap items-center justify-start">
        <!-- 打开模型供应商列表的按钮 -->
        <Button
          v-if="isMobile"
          variant="ghost"
          class="mr-2 h-8 w-8 rounded p-0"
          :aria-label="t('model.openProviderList') as string"
          @click="chatPageStore.toggleDrawer()"
        >
          <Menu class="h-5 w-5" />
        </Button>
        <!-- 快速预览选中模型 -->
        <Button
          v-if="checkedModelList.length > 0"
          variant="outline"
          size="sm"
          class="mr-2"
          :aria-label="t('common.a11y.clearSelection') as string"
          @click="checkedModelIdList = []"
        >
          <Trash2 class="h-4 w-4" />
        </Button>
        <Badge
          v-for="model in checkedModelList"
          :key="model.id"
          variant="secondary"
          class="mr-1 cursor-pointer"
          @click="deleteCheckModelId(model)"
        >
          {{ model.nickname }}
          <button
            class="ml-1 hover:text-destructive"
            @click.stop="deleteCheckModelId(model)"
          >
            ×
          </button>
        </Badge>
      </div>
      <!-- 操作区域 -->
      <div class="flex h-full items-center justify-end">
        <Button :disabled="confirmLoading" @click="onConfirm">
          {{ t('common.confirm') }}
        </Button>
        <FilterInput
          :model-value="filterText"
          @update:model-value="setFilterText"
          :placeholder="t('chat.searchPlaceholder') as string"
          class="ml-2 h-8 w-72!"
        />
      </div>
    </div>
    <!-- 模型列表 -->
    <DataTable
      :columns="columns"
      :data="filteredModels"
      row-key="id"
      :loading="loading"
      class="ml-1 mr-1"
    />
  </div>
</template>

// src/pages/Chat/components/ChatContent/components/ModelSelect.tsx
import FilterInput from "@/components/FilterInput";
import { useAppDispatch, useAppSelector } from "@/hooks/redux";
import { useBasicModelTable } from "@/hooks/useBasicModelTable";
import { useCurrentSelectedChat } from "@/hooks/useCurrentSelectedChat";
import { editChat } from "@/store/slices/chatSlices";
import { toggleDrawer } from "@/store/slices/chatPageSlices";
import { Chat } from "@/types/chat";
import { Model } from "@/types/model";
import { Trash2, Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { DataTable } from "@/components/ui/data-table";
import { toast } from "sonner";
import { isUndefined } from "es-toolkit";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { ColumnDef } from "@tanstack/react-table";
import { useResponsive } from "@/hooks/useResponsive";

/**
 * @description 新建聊天的时候提供选择模型
 */
const ModelSelect: React.FC = () => {
  const dispatch = useAppDispatch();
  const { t } = useTranslation();
  const { isMobile } = useResponsive();
  const selectedChat = useCurrentSelectedChat();

  // 打开抽屉
  const openDrawer = () => {
    dispatch(toggleDrawer());
  };

  const typedSelectedChat = selectedChat as Chat;

  const { filterText, filteredModels, setFilterText, tableColumns } =
    useBasicModelTable();

  const models = useAppSelector((state) => state.models.models);
  const loading = useAppSelector((state) => state.models.loading);

  // 选中的模型ID的列表
  const [checkedModelIdList, setCheckedModelIdList] = useState<string[]>([]);

  // 添加选中的ID
  const addCheckModelId = (model: Model) => {
    setCheckedModelIdList([...checkedModelIdList, model.id]);
  };

  // 删除选中的ID
  const deleteCheckModelId = (model: Model) => {
    const idx = checkedModelIdList.findIndex((item) => item === model.id);
    if (idx !== -1) {
      const newList = [...checkedModelIdList];
      newList.splice(idx, 1);
      setCheckedModelIdList(newList);
    }
  };

  // 从 redux 中计算出模型列表
  const checkedModelList = useMemo<Model[]>(() => {
    const list: Model[] = [];
    checkedModelIdList.forEach((id) => {
      const model = models.find((item) => item.id === id);
      if (!isUndefined(model)) {
        list.push(model);
      }
    });
    return list;
  }, [models, checkedModelIdList]);

  // 表格相关配置（添加选择列）
  const columns: ColumnDef<Model>[] = [
    {
      id: "selected",
      header: "",
      cell: ({ row }) => (
        <Checkbox
          checked={checkedModelIdList.includes(row.original.id)}
          onCheckedChange={(checked) => {
            if (checked) {
              addCheckModelId(row.original);
            } else {
              deleteCheckModelId(row.original);
            }
          }}
        />
      ),
    },
    ...tableColumns,
  ];

  // 确认按钮的 loading 状态
  const [confirmLoading, setConfirmLoading] = useState(false);

  // 点击确定创建聊天
  const onConfirm = async () => {
    if (checkedModelIdList.length <= 0) {
      toast.info(t(($) => $.chat.selectModelHint));
      return;
    }

    setConfirmLoading(true);

    try {
      await dispatch(
        editChat({
          chat: {
            ...typedSelectedChat,
            chatModelList: checkedModelIdList.map((id) => ({
              modelId: id,
              chatHistoryList: [],
            })),
          },
        }),
      );

      toast.success(
        t(($) => $.chat.configureChatSuccess),
        {
          position: "top-right",
        },
      );
    } catch {
      toast.error(
        t(($) => $.chat.configureChatFailed),
        {
          position: "top-right",
        },
      );
    }

    setConfirmLoading(false);
  };

  return (
    <>
      <div className="flex justify-between w-full h-12 pl-4 pr-4">
        <div className="flex flex-wrap items-center justify-start h-full">
          {/* 打开模型供应商列表的按钮 */}
          {isMobile && (
            <Button
              variant="ghost"
              className="rounded mr-2 h-8 w-8 p-0"
              onClick={openDrawer}
              aria-label="打开模型供应商列表"
            >
              <Menu className="h-5 w-5" />
            </Button>
          )}
          {/* 快速预览选中模型 */}
          {checkedModelList.length > 0 && (
            <Button
              variant="outline"
              size="sm"
              className="mr-2"
              onClick={() => {
                // 清空所有选中
                setCheckedModelIdList([]);
              }}
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          )}
          {checkedModelList.map((model: Model) => {
            return (
              <Badge
                key={model.id}
                variant="secondary"
                className="mr-1 cursor-pointer"
                onClick={() => deleteCheckModelId(model)}
              >
                {model.nickname}
                <button
                  className="ml-1 hover:text-destructive"
                  onClick={(e) => {
                    e.stopPropagation();
                    deleteCheckModelId(model);
                  }}
                >
                  ×
                </button>
              </Badge>
            );
          })}
        </div>
        {/* 操作区域 */}
        <div className="flex items-center justify-end h-full">
          <Button onClick={onConfirm} disabled={confirmLoading}>
            {t(($) => $.common.confirm)}
          </Button>
          <FilterInput
            value={filterText}
            onChange={setFilterText}
            placeholder={t(($) => $.chat.searchPlaceholder)}
            className="h-8 ml-2 w-72!"
          />
        </div>
      </div>
      {/* 模型列表 */}
      <DataTable
        columns={columns}
        data={filteredModels}
        rowKey="id"
        loading={loading}
        className="ml-1 mr-1"
      />
    </>
  );
};

export default ModelSelect;
