// src/pages/Setting/components/GeneralSetting/components/ModelProviderSetting/components/ProviderCardHeader.vue
<script setup lang="ts">
import { useTranslation } from 'i18next-vue';
import { CheckCircle, XCircle, ChevronDown, ChevronUp } from 'lucide-vue-next';
import { Badge } from '@/components/ui/badge';
import { ProviderLogo } from '@/components/ProviderLogo';

/**
 * 供应商卡片头部组件属性
 */
interface ProviderCardHeaderProps {
  /** 供应商名称 */
  providerName: string;
  /** 供应商唯一标识 */
  providerKey: string;
  /** 供应商状态 */
  status: 'available' | 'unavailable';
  /** 是否展开 */
  isExpanded: boolean;
}

const props = defineProps<ProviderCardHeaderProps>();

const { t } = useTranslation();
</script>

<!-- 供应商卡片头部：名称、状态图标、展开/折叠图标 -->
<template>
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-3">
      <ProviderLogo
        :provider-key="props.providerKey"
        :provider-name="props.providerName"
        :size="40"
      />
      <h3 class="font-semibold text-lg">{{ props.providerName }}</h3>
      <Badge
        v-if="props.status === 'available'"
        variant="outline"
        class="gap-1 text-green-600 border-green-600"
      >
        <CheckCircle class="w-3 h-3" />
        {{ t('setting.modelProvider.status.available') }}
      </Badge>
      <Badge
        v-else
        variant="outline"
        class="gap-1 text-red-600 border-red-600"
      >
        <XCircle class="w-3 h-3" />
        {{ t('setting.modelProvider.status.unavailable') }}
      </Badge>
    </div>
    <div class="text-muted-foreground">
      <ChevronUp v-if="props.isExpanded" class="w-5 h-5" />
      <ChevronDown v-else class="w-5 h-5" />
    </div>
  </div>
</template>

// src/pages/Setting/components/GeneralSetting/components/ModelProviderSetting/components/ProviderCardHeader.tsx
import React from 'react';
import { CheckCircle, XCircle, ChevronDown, ChevronUp } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { useTranslation } from 'react-i18next';
import { ProviderLogo } from '@/components/ProviderLogo';

/**
 * ProviderCardHeader 组件的属性
 */
interface ProviderCardHeaderProps {
  /** 供应商名称 */
  providerName: string;
  /** 供应商唯一标识 */
  providerKey: string;
  /** 供应商状态 */
  status: 'available' | 'unavailable';
  /** 是否展开 */
  isExpanded: boolean;
}

/**
 * 供应商卡片头部组件
 * 显示供应商名称、状态图标、展开/折叠图标
 */
export const ProviderCardHeader = React.memo<ProviderCardHeaderProps>(
  ({ providerName, providerKey, status, isExpanded }) => {
    const { t } = useTranslation();

    return (
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <ProviderLogo
            providerKey={providerKey}
            providerName={providerName}
            size={40}
          />
          <h3 className="font-semibold text-lg">{providerName}</h3>
          {status === 'available' ? (
            <Badge variant="outline" className="gap-1 text-green-600 border-green-600">
              <CheckCircle className="w-3 h-3" />
              {t($ => $.setting.modelProvider.status.available)}
            </Badge>
          ) : (
            <Badge variant="outline" className="gap-1 text-red-600 border-red-600">
              <XCircle className="w-3 h-3" />
              {t($ => $.setting.modelProvider.status.unavailable)}
            </Badge>
          )}
        </div>
        <div className="text-muted-foreground">
          {isExpanded ? (
            <ChevronUp className="w-5 h-5" />
          ) : (
            <ChevronDown className="w-5 h-5" />
          )}
        </div>
      </div>
    );
  }
);

ProviderCardHeader.displayName = 'ProviderCardHeader';
