// src/pages/Setting/components/SettingSidebar.tsx
import { useAdaptiveScrollbar } from "@/hooks/useAdaptiveScrollbar";
import { Button } from "@/components/ui/button";
import { useMemo, useRef, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { useLocation, useNavigate } from "react-router-dom";
import { useResponsive } from "@/hooks/useResponsive";

interface SettingButton {
  name: string;
  path: string;
}

/**
 * 设置页面侧边栏
 * @description 支持按钮压缩：根据屏幕尺寸调整按钮高度和文字大小
 */
const SettingSidebar: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { isDesktop } = useResponsive();

  // 用来标识当前选中的哪个按钮
  const selectedBtnPath = useMemo<string | null | undefined>(() => {
    const key = location.pathname.split("/")[2];
    return key;
  }, [location]);
  const { t } = useTranslation();

  const { onScrollEvent, scrollbarClassname } = useAdaptiveScrollbar();

  // 滚动容器 ref
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // 需要渲染的按钮列表
  const settingList = useMemo<SettingButton[]>(() => {
    const list = [
      {
        name: t(($) => $.setting.generalSetting),
        path: "common",
      },
      {
        name: t(($) => $.setting.keyManagement.title),
        path: "key-management",
      },
    ];

    // 仅开发环境显示 Toast 测试按钮
    if (import.meta.env.DEV) {
      list.push({
        name: t(($) => $.setting.toastTest),
        path: "toast-test",
      });
    }

    return list;
  }, [t]);

  // 点击某一类设置按钮的回调
  const onClickSettingBtn = (btn: SettingButton) => {
    const { path } = btn;

    if (selectedBtnPath === path) return;

    navigate(path);
  };

  // 添加 passive 监听器
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    container.addEventListener("scroll", onScrollEvent, { passive: true });

    return () => {
      container.removeEventListener("scroll", onScrollEvent);
    };
  }, [onScrollEvent]);

  // 按钮样式根据屏幕尺寸压缩（参考 ChatButton 的压缩逻辑）
  const buttonClassName = `w-full mb-2 ${
    !isDesktop ? "h-9 text-sm" : "h-11 text-base"
  }`;

  return (
    <nav
      ref={scrollContainerRef}
      aria-label={t(($) => $.common.a11y.settingsNav)}
      className={`p-2 overflow-y-auto w-full h-full
      flex flex-col justify-start items-center
      ${scrollbarClassname}
    `}
    >
      {settingList.map((item) => {
        return (
          <Button
            key={item.path}
            variant="default"
            size="lg"
            className={buttonClassName}
            aria-current={selectedBtnPath === item.path ? 'page' : undefined}
            onClick={() => onClickSettingBtn(item)}
          >
            {item.name}
          </Button>
        );
      })}
    </nav>
  );
};

export default SettingSidebar;

// src/pages/Setting/components/SettingSidebar.vue
<script setup lang="ts">
/**
 * 设置页面侧边栏（对应旧版 SettingSidebar.tsx）
 * 支持按钮压缩：根据屏幕尺寸调整按钮高度和文字大小
 */
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { Button } from '@/components/ui/button';
import { useResponsive } from '@/composables/useResponsive';
import { useTranslation } from '@/composables/useTranslation';
import { useAdaptiveScrollbar } from '@/composables/useAdaptiveScrollbar';

/** 设置按钮 */
interface SettingButton {
  name: string;
  path: string;
}

const route = useRoute();
const router = useRouter();
const { isDesktop } = useResponsive();
const { t } = useTranslation();
const { onScrollEvent, scrollbarClassname } = useAdaptiveScrollbar();

// 用来标识当前选中的哪个按钮
const selectedBtnPath = computed<string | null>(() => {
  const key = route.path.split('/')[2];
  return key ?? null;
});

// 需要渲染的按钮列表
const settingList = computed<SettingButton[]>(() => {
  const list: SettingButton[] = [
    { name: t('setting.generalSetting'), path: 'common' },
    { name: t('setting.keyManagement.title'), path: 'key-management' },
  ];

  // 仅开发环境显示 Toast 测试按钮
  if (import.meta.env.DEV) {
    list.push({ name: t('setting.toastTest'), path: 'toast-test' });
  }

  return list;
});

/** 点击某一类设置按钮的回调 */
const onClickSettingBtn = (btn: SettingButton): void => {
  const { path } = btn;

  if (selectedBtnPath.value === path) return;

  void router.push(path);
};

// 按钮样式根据屏幕尺寸压缩
const buttonClassName = computed(
  () => `mb-2 w-full ${!isDesktop.value ? 'h-9 text-sm' : 'h-11 text-base'}`,
);
</script>

<template>
  <nav
    :aria-label="t('common.a11y.settingsNav')"
    :class="`flex h-full w-full flex-col items-center justify-start overflow-y-auto p-2 ${scrollbarClassname}`"
    @scroll="onScrollEvent"
  >
    <Button
      v-for="item in settingList"
      :key="item.path"
      variant="default"
      size="lg"
      :class="buttonClassName"
      :aria-current="selectedBtnPath === item.path ? 'page' : undefined"
      @click="onClickSettingBtn(item)"
    >
      {{ item.name }}
    </Button>
  </nav>
</template>
