// src/pages/Chat/components/Sidebar/ChatSidebar.vue
<script setup lang="ts">
/**
 * 聊天侧边栏组件（对应旧版 pages/Chat/components/Sidebar/index.tsx）
 * 搜索过滤 + 虚拟滚动会话列表
 */
import { ref, computed } from 'vue';
import { storeToRefs } from 'pinia';
import { VList } from 'virtua/vue';
import ToolsBar from './components/ToolsBar.vue';
import { Skeleton } from '@/components/ui/skeleton';
import { useDebouncedFilter } from '@/composables/useDebouncedFilter';
import { useChatStore } from '@/stores';
import { useAdaptiveScrollbar } from '@/composables/useAdaptiveScrollbar';
import ChatButton from './components/ChatButton.vue';
import { useExistingChatList } from '@/composables/useExistingChatList';
import type { ChatMeta } from '@/types/chat';

const chatStore = useChatStore();
const { loading: chatListLoading, selectedChatId } = storeToRefs(chatStore);
const chatMetaList = useExistingChatList();

const { onScrollEvent, scrollbarClassname } = useAdaptiveScrollbar();

const filterText = ref('');

/** 过滤谓词：按名称模糊匹配 */
const filterPredicate = (meta: ChatMeta): unknown =>
  meta.name?.toLocaleLowerCase().includes(filterText.value.toLocaleLowerCase());

const { filteredList: filteredChatList } = useDebouncedFilter<ChatMeta>(
  () => filterText.value,
  () => chatMetaList.value,
  filterPredicate,
);

// 供模板使用的 computed 别名
const chatList = computed(() => filteredChatList.value);
</script>

<template>
  <div
    data-testid="chat-sidebar"
    class="relative flex h-full w-full flex-col items-center justify-start"
  >
    <div class="h-12 w-full border-b border-gray-100 p-2">
      <ToolsBar
        :filter-text="filterText"
        @update:filter-text="(v: string) => (filterText = v)"
      />
    </div>
    <div v-if="!chatListLoading" class="w-full min-h-0 flex-1">
      <VList
        :class="`w-full pb-2 ${scrollbarClassname}`"
        :data="chatList"
        @scroll="onScrollEvent"
      >
        <template #default="{ item: meta }">
          <ChatButton
            :chat-meta="meta"
            :is-selected="meta.id === selectedChatId"
          />
        </template>
      </VList>
    </div>
    <div v-else class="w-full space-y-2 p-2">
      <Skeleton v-for="index in 5" :key="index" class="h-11 w-full" />
    </div>
  </div>
</template>

// src/pages/Chat/components/ChatSidebar/index.tsx
import ToolsBar from "./components/ToolsBar"
import { Spin } from "antd"
import { useState } from "react"
import { useDebouncedFilter } from "@/components/FilterInput/hooks/useDebouncedFilter"
import { useAppSelector } from "@/hooks/redux"
import { useAdaptiveScrollbar } from "@/hooks/useAdaptiveScrollbar"
import ChatButton from "./components/ChatButton"
import { useExistingChatList } from "@/hooks/useExistingChatList"

const ChatSidebar: React.FC = () => {
  const chatList = useExistingChatList()
  const chatListLoading = useAppSelector((state) => state.chat.loading)

  // 控制滚动条的相关逻辑
  const {
    onScrollEvent,
    scrollbarClassname,
  } = useAdaptiveScrollbar()

  // 本地状态：过滤文本
  const [filterText, setFilterText] = useState<string>('')

  const {
    filteredList: filteredChatList,
  } = useDebouncedFilter(
    filterText,
    chatList,
    (chat) => chat.name?.toLocaleLowerCase().includes(filterText.toLocaleLowerCase()),
  )

  return (
    <div className="relative flex flex-col items-center justify-start w-full h-full">
      <div className="w-full h-12 p-2 border-b border-gray-100">
        <ToolsBar
          filterText={filterText}
          onFilterChange={setFilterText}
        />
      </div>
      <div
        className={`pb-2 overflow-y-auto w-full
          ${scrollbarClassname}
        `}
        onScroll={onScrollEvent}
      >
        {/* 带有 loading 效果 */}
        {!chatListLoading ? filteredChatList.map(chat => {
          return <ChatButton
            chat={chat}
            key={chat.id}
          />
        }) : <Spin spinning={chatListLoading} tip="加载中">
          <div className="w-full min-h-40"></div>
        </Spin>}
      </div>
    </div>
  )
}


export default ChatSidebar
